POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktpbmdPZlNwYXJ0YSIsImlkIjoiNWVhMmI4NTI0YjhiODc2Y2E1NjI2MWFmIiwiaWF0IjoxNTg3NzMwMjcyfQ.gLsOxkWfUh9ggRtfAnzzYBv6A7sQHXzTKRTlt6RTVYQ

{
  "title": "A walk with 300",
  "author": "King Leonidas",
  "url": "https://www.300.com",
  "likes": 300
}